// Auto-generated by: pnpm db:types
// Replace <YOUR_PROJECT_ID> in package.json then run `pnpm db:types` to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      accounts: {
        Row: {
          id: string
          owner_id: string
          name: string
          kind: 'cash' | 'bank' | 'card' | 'ewallet'
          opening_balance: number
          archived: boolean
          created_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          kind: 'cash' | 'bank' | 'card' | 'ewallet'
          opening_balance?: number
          archived?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          kind?: 'cash' | 'bank' | 'card' | 'ewallet'
          opening_balance?: number
          archived?: boolean
          created_at?: string
        }
        Relationships: []
      }
      categories: {
        Row: {
          id: string
          owner_id: string | null
          name: string
          icon: string
          color: string
          created_at: string
        }
        Insert: {
          id?: string
          owner_id?: string | null
          name: string
          icon: string
          color: string
          created_at?: string
        }
        Update: {
          id?: string
          owner_id?: string | null
          name?: string
          icon?: string
          color?: string
          created_at?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          id: string
          owner_id: string
          type: 'expense' | 'income' | 'transfer'
          amount: number
          category_id: string | null
          account_id: string
          to_account_id: string | null
          merchant: string
          note: string | null
          date: string
          receipt_url: string | null
          subscription_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          type: 'expense' | 'income' | 'transfer'
          amount: number
          category_id?: string | null
          account_id: string
          to_account_id?: string | null
          merchant: string
          note?: string | null
          date: string
          receipt_url?: string | null
          subscription_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          type?: 'expense' | 'income' | 'transfer'
          amount?: number
          category_id?: string | null
          account_id?: string
          to_account_id?: string | null
          merchant?: string
          note?: string | null
          date?: string
          receipt_url?: string | null
          subscription_id?: string | null
          created_at?: string
        }
        Relationships: []
      }
      budgets: {
        Row: {
          id: string
          owner_id: string
          category_id: string
          amount: number
          period: string
          start_month: string
          created_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          category_id: string
          amount: number
          period?: string
          start_month?: string
          created_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          category_id?: string
          amount?: number
          period?: string
          start_month?: string
          created_at?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          id: string
          owner_id: string
          name: string
          amount: number
          type: 'expense' | 'income'
          category_id: string | null
          account_id: string
          cadence: 'monthly' | 'yearly'
          day_of_month: number
          month_of_year: number
          next_due_date: string
          note: string | null
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          amount: number
          type: 'expense' | 'income'
          category_id?: string | null
          account_id: string
          cadence: 'monthly' | 'yearly'
          day_of_month: number
          month_of_year: number
          next_due_date: string
          note?: string | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          amount?: number
          type?: 'expense' | 'income'
          category_id?: string | null
          account_id?: string
          cadence?: 'monthly' | 'yearly'
          day_of_month?: number
          month_of_year?: number
          next_due_date?: string
          note?: string | null
          active?: boolean
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
