// Generates docs/specs/INDEX.md from every docs/specs/*/PLAN.md + EXECUTION.md.
// Contract: EXECUTION.md STATUS blocks must match the canonical format documented in
// docs/specs/spec-index/PLAN.md — this parser is deliberately strict and exits nonzero
// naming the offending file rather than rendering a silently wrong board.
//
// Usage: node scripts/spec-index.mjs   (or: pnpm specs:index)

import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { collectSpecRecords, SpecStatusError } from './spec-status.mjs'

const SPECS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'specs')

let rows
let referenceRows
try {
  ;({ rows, referenceRows } = collectSpecRecords(SPECS_DIR))
} catch (err) {
  if (err instanceof SpecStatusError) {
    console.error(`spec-index: ${err.message}`)
    process.exit(1)
  }
  throw err
}

const out = [
  '# Specs Index',
  '',
  '_Generated by `pnpm specs:index` — do not edit. Derived report only: on any conflict,_',
  '_git and `EXECUTION.md` STATUS blocks win._',
  '',
  '| Spec | Status | Phases | Debt | Description |',
  '|------|--------|--------|------|-------------|',
  ...rows.map((r) => `| [${r.slug}](${r.slug}/PLAN.md) | ${r.status} | ${r.phases} | ${r.debt} | ${r.description} |`),
]
if (referenceRows.length > 0) {
  out.push(
    '',
    '## Reference',
    '',
    '| Doc | Description |',
    '|-----|-------------|',
    ...referenceRows.map((r) => `| [${r.slug}](${r.slug}/PLAN.md) | ${r.description} |`),
  )
}
out.push('')

writeFileSync(join(SPECS_DIR, 'INDEX.md'), out.join('\n'))
console.log(`spec-index: wrote docs/specs/INDEX.md (${rows.length} specs, ${referenceRows.length} reference)`)
